version: '3'

services:
  shoppingcartapi:
    image: shoppingcartapi
    environment:
      - ConnectionString=shoppingcart.data
    build:
      context: ./ShoppingCartApi
      dockerfile: Dockerfile
    depends_on:
      - shoppingcart.data
      - sql.data
  shoppingcart.data:
    image: redis
  sql.data:
    image: microsoft/mssql-server-linux
