version: '3'

services:
  shoppingcartapi:
    image: shoppingcartapi
    build:
      context: ./ShoppingCartApi
      dockerfile: Dockerfile
    depends_on:
      - shoppingcart.data
  shoppingcart.data:
    image: redis
    ports:
      - "6379:6379"
