version: '3'

services:
  shoppingcartapi:
    image: shoppingcartapi
    environment:
      - ConnectionString=shoppingcart.data
    build:
      context: ./ShoppingCartApi
      dockerfile: Dockerfile
    depends_on:
      - shoppingcart.data
      - shoppingcartsql.data
  shoppingcart.data:
    image: redis
  shoppingcartsql.data:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

